export default [
  { id:  1, number:  2, position: 'QB',      name: { family: '紺野', first: '恭平' },   kana: { first: 'Kyohei',    family: 'Konno'     } },
  { id:  2, number:  3, position: 'QB',      name: { family: '萩野', first: '悠斗' },   kana: { first: 'Yuto',      family: 'Hagino'    } },
  { id:  3, number:  4, position: 'LB',      name: { family: '高山', first: '和彦' },   kana: { first: 'Kazuhiko',  family: 'Takayama'  } },
  { id:  4, number:  5, position: 'RB',      name: { family: '福島', first: '豪'   },   kana: { first: 'Tsuyoshi',  family: 'Fukushima' } },
  { id:  5, number:  6, position: 'LB',      name: { family: '廣岡', first: '亮'   },   kana: { first: 'Ryo',       family: 'Hirooka'   } },
  { id:  6, number:  7, position: 'WR',      name: { family: '小泉', first: '翼'   },   kana: { first: 'Tsubasa',   family: 'Koizumi'   } },
  { id:  7, number:  8, position: 'QB',      name: { family: '柿沼', first: '達也' },   kana: { first: 'Tatsuya',   family: 'Kakinuma'  } },
  { id:  8, number:  9, position: 'TE',      name: { family: '渡邊', first: '玄器' },   kana: { first: 'Genki',     family: 'Watanabe'  } },
  { id:  9, number: 10, position: 'WR',      name: { family: '林',   first: '茂樹' },   kana: { first: 'Shigeki',   family: 'Hayashi'   } },
  { id: 10, number: 11, position: 'DB',      name: { family: '杜',   first: '英俊' },   kana: { first: 'Hidetoshi', family: 'Mori'      } },
  { id: 11, number: 12, position: 'QB',      name: { family: '江川', first: '主民' },   kana: { first: 'Kazme',     family: 'Egawa'     } },
  { id: 12, number: 13, position: 'DB',      name: { family: '菅原', first: '崇大' },   kana: { first: 'Takahiro',  family: 'Sugawara'  } },
  { id: 13, number: 19, position: 'WR',      name: { family: '窪田', first: '塁' },     kana: { first: 'Rui',       family: 'Kubota'    } },
  { id: 14, number: 23, position: 'RB',      name: { family: '長嶺', first: '将彦' },   kana: { first: 'Masahiko',  family: 'Nagamine'  } },
  { id: 15, number: 24, position: 'RB',      name: { family: '一丸', first: '慎太郎' }, kana: { first: 'Shintaro',  family: 'Ichimaru'  } },
  { id: 16, number: 27, position: 'DB',      name: { family: '新川', first: '聖也' },   kana: { first: 'Seiya',     family: 'Shinkawa'  } },
  { id: 17, number: 29, position: 'WR',      name: { family: '松岡', first: '慶樹' },   kana: { first: 'Yoshiki',   family: 'Matsuoka'  } },
  { id: 18, number: 35, position: 'DB',      name: { family: '松尾', first: '勇佐' },   kana: { first: 'Yusuke',    family: 'Matsuo'    } },
  { id: 19, number: 39, position: 'RB',      name: { family: '山口', first: '拓弥' },   kana: { first: 'Takuya',    family: 'Yamaguchi' } },
  { id: 20, number: 40, position: 'LB',      name: { family: '鈴木', first: '翔太' },   kana: { first: 'Shota',     family: 'Suzuki'    } },
  { id: 21, number: 47, position: 'LB',      name: { family: '坂田', first: '和也' },   kana: { first: 'Kazuya',    family: 'Sakata'    } },
  { id: 22, number: 55, position: 'OT',      name: { family: '雨宮', first: '明和' },   kana: { first: 'Akekazu',   family: 'Amemiya'   } },
  { id: 23, number: 56, position: 'DL',      name: { family: '近藤', first: '圭介' },   kana: { first: 'Keisuke',   family: 'Kondo'     } },
  { id: 24, number: 57, position: 'DL',      name: { family: '三浦', first: '翔' },     kana: { first: 'Sho',       family: 'Miura'     } },
  { id: 25, number: 58, position: 'OL',      name: { family: '木下', first: '岳士' },   kana: { first: 'Takeshi',   family: 'Kinoshita' } },
  { id: 26, number: 62, position: 'OL',      name: { family: '松浦', first: '恒太' },   kana: { first: 'Kouta',     family: 'Matsuura'  } },
  { id: 27, number: 66, position: 'DL',      name: { family: '堀口', first: '文人' },   kana: { first: 'Ayato',     family: 'Horiguchi' } },
  { id: 28, number: 69, position: 'DL',      name: { family: '梅澤', first: '伸夫' },   kana: { first: 'Nobuo',     family: 'Umezawa'   } },
  { id: 29, number: 73, position: 'OL',      name: { family: '渕上', first: '雄介' },   kana: { first: 'Yusuke',    family: 'Fuchigami' } },
  { id: 30, number: 75, position: 'OL / DL', name: { family: '伊藤', first: '洋' },     kana: { first: 'Hiroshi',   family: 'Ito'       } },
  { id: 31, number: 78, position: 'DT',      name: { family: '金子', first: '宏貴' },   kana: { first: 'Hiroki',    family: 'Kaneko'    } },
  { id: 32, number: 81, position: 'WR',      name: { family: '橘',   first: '俊樹' },   kana: { first: 'Toshiki',   family: 'Tachibana' } },
  { id: 33, number: 99, position: 'WR',      name: { family: '矢竹', first: '雄一郎' }, kana: { first: 'Yuichiro',  family: 'Yatake'    } },
]
